name: Build and Publish Android App

on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Type of version increment (major, minor, patch)'
        required: false
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to get all tags

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/JetBrains/Amper
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-amper-${{ hashFiles('**/module.xml', 'amper', 'amper.bat', 'gradle/*.versions.toml') }}

      - name: Retrieve the secret and decode it to a file
        env:
          KEYFILE_BASE64: ${{ secrets.KEYFILE_BASE64 }}
        run: |
          echo "$KEYFILE_BASE64" | base64 --decode > keystore.jks

      - name: Get latest git tag and increment version
        id: get_version
        env:
          BUMP_TYPE: ${{ github.event.inputs.version_bump_type }}
        run: bash .github/scripts/get_version.sh

      - name: Create and push new git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Write new keystore.properties file
        run: |
          echo "storeFile=${{ github.workspace }}/keystore.jks" > keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Set the version name and version code on the module.yaml file
        run: bash .github/scripts/set_version.sh
        env:
          VERSION_CODE: ${{ env.NEW_VERSION_CODE }}
          VERSION_NAME: ${{ env.NEW_VERSION }}

      - name: Build Release Android app
        run: |
          ./amper package \
            --module TimeKeeper \
            --platform android \
            --variant release \
            --format aab

      - name: Generate Google Play credentials
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Publish app to Play Store
        # https://github.com/r0adkll/upload-google-play/releases/tag/v1.1.3
        uses: r0adkll/upload-google-play@935ef9c68bb393a8e6116b1575626a7f5be3a7fb
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: dev.sal.timekeeper
          releaseFiles: ${{ github.workspace }}/build/tasks/_TimeKeeper_bundleAndroid/gradle-project/build/_/outputs/bundle/release/gradle-project-release.aab
          changesNotSentForReview: true

      - name: Upload the AAB
        uses: actions/upload-artifact@v4
        with:
          name: TimeKeeper-release-${{ env.NEW_VERSION }}.aab
          path: ${{ github.workspace }}/build/tasks/_TimeKeeper_bundleAndroid/gradle-project/build/_/outputs/bundle/release/gradle-project-release.aab