name: Build and Publish Android App

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Version for the Android app'
        required: true
        type: string
      app_version_name:
        description: 'Version name for the Android app (i.e. v0.2.1)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Retrieve the secret and decode it to a file
        env:
          KEYFILE_BASE64: ${{ secrets.KEYFILE_BASE64 }}
        run: |
          echo $KEYFILE_BASE64 | base64 --decode > keystore.jks
      - name: Build Release Android app
        env:
          KEYFILE: ${{ github.workspace }}/keystore.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          VERSION_CODE: ${{ inputs.app_version }}
          VERSION_NAME: ${{ inputs.app_version_name }}
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
        run: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$KEYFILE \
            -Pandroid.injected.signing.store.password=$STORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Generate Google Play credentials
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: Publish app to Play Store
        # https://github.com/r0adkll/upload-google-play/releases/tag/v1.1.3
        uses: r0adkll/upload-google-play@935ef9c68bb393a8e6116b1575626a7f5be3a7fb
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: dev.sal.timekeeper
          releaseFiles: ${{ github.workspace }}/build/outputs/bundle/release/TimeKeeper-release.aab
          track: internal
          status: draft
      - name: Upload the AAB
        uses: actions/upload-artifact@v4
        with:
          name: TimeKeeper-release-${{ inputs.app_version_name }}.aab
          path: ${{ github.workspace }}/build/outputs/bundle/release/TimeKeeper-release.aab